"""add column owner_id in table links

Revision ID: afdcf02236d2
Revises: bf5685c6f83d
Create Date: 2022-02-04 15:50:05.439137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdcf02236d2'
down_revision = 'bf5685c6f83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'links', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_column('links', 'owner_id')
    # ### end Alembic commands ###
