"""add cascade for table links

Revision ID: ca4c00939fbb
Revises: afdcf02236d2
Create Date: 2022-07-14 15:13:41.902412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4c00939fbb'
down_revision = 'afdcf02236d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
